name: Closed Issue Message

on:
  issues:
    types:
      - closed

permissions:
  issues: write

jobs:
  auto_comment:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/closed-issue-message@8b6324312193476beecf11f8e8539d73a3553bf4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          message: |
            ### ⚠️ COMMENT VISIBILITY WARNING ⚠️
            Comments on closed issues are hard for our team to see.
            If you need more assistance, please either tag a team member or open a new issue that references this one.
            If you wish to keep having a conversation with other community members under this issue feel free to do so.
