name: Run unit tests and builds the project

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [20, 21]
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Set node version
        uses: actions/setup-node@26961cf329f22f6837d5f54c3efd76b480300ace
        with:
          node-version: ${{ matrix.version }}
      - name: Install dependencies
        run: npm install
      - name: Build all packages
        run: npm run build
      - name: Run linting
        run: npm run lint
      - name: Run unit tests
        run: npm test
