name: Run lint checks on the project

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Link Checker
        uses: lycheeverse/lychee-action@c053181aa0c3d17606addfe97a9075a32723548a
        with:
          fail: true
          args: --scheme=https . --exclude-all-private
      - name: Install dependencies
        run: npm install
      - name: Run linting
        run: npm run lint
      - name: Spell check
        uses: streetsidesoftware/cspell-action@4dc9d4bdf3974ed26d6f2e973c1e168edff47d80
        with:
          files: '**/*.{md,ts}'
          strict: true
          check_dot_files: true
          incremental_files_only: false
          config: 'cspell.config.yml'
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@cd81f4475ab741e097ec0fe73b692f3e49d66b8c
        with:
          scandir: '.'
          ignore_paths: >-
            node_modules
            .husky
